name: fumbbl_data_get
description: API to access data from fumbbl.
version: 1.0.0

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  requests: ^4.7.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
